CH03 EGL 초기화 예제 추가.
daemyung/learn-opengl-es pull request #10
Opened 2023-08-30 12:24 UTC by WongueShin

## 🙏 Describe the pull request

glfw3 을 이용해 EGL 윈도우를 생성하는 예제입니다.

Resolves #
* ch03 initialize egl 예제를 추가합니다
* 이미 suppress 로 코드 퀄리티 유지에 도움을 주지 못하는 cppcheck 를 비활성화합니다.
* draw tetrahedron 포멧을 clang-format 에 알맞게 수정합니다.

## 💬 Additional context
vcpkg 를 의존합니다.
angle 과 glfw3 이 로컬에 설치되어야합니다.

## 🖥️ System
- OS: XOS
- GPU: m2
- OpenGL: OpenGL ES 3.0
- EGL: GLFW3, EGL

## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated, if necessary.

2023-08-30 12:35 UTC, arduinocc04 requested changes

2023-08-30 12:35 UTC, arduinocc04 commented on ch03/CMakeLists.txt
> +project(OpenGLES)
프로젝트 이름을 바꾸는 것이 좋을것 같아요.
또한, 새로 project를 만드신 이유가 있을까요?
루트에 subdirs로 추가하고, `add_executable`만 사용할 수는 없나요?

2023-08-30 12:35 UTC, arduinocc04 commented on ch03/initEGL/initEGL.c
> +  EGLint configAttribs[] = {EGL_RED_SIZE,  8, EGL_GREEN_SIZE, 8,
여기 스페이스 2개 들어가있어요

2023-08-30 12:38 UTC, WongueShin commented on ch03/CMakeLists.txt
> +project(OpenGLES)
기존 프로젝트하고 의존성이 꼬이더군요...
저자의 esUtill 함수들을 최대한 사용해보고 싶었는데, 생각보다 너무 대규모작업이라 포기했습니다.

이 추가되는 예제는 glfw3, angle 을 의존하는데, 제가 알기론 리눅스, 윈도우, xos 세OS 에서 모두 문제없이 빌드 가능한것으로 알고있어요.

2023-08-30 12:42 UTC, Wongyu-Shin commented on ch03/initEGL/initEGL.c
> +  EGLint configAttribs[] = {EGL_RED_SIZE,  8, EGL_GREEN_SIZE, 8,
이해는 되지 않다만... 이렇게 clang-format 이 시키네요
```
+++ formatted

@@ -29,7 +29,7 @@

 
   // EGL 구성 선택
   EGLConfig config;
-  EGLint configAttribs[] = {EGL_RED_SIZE, 8, EGL_GREEN_SIZE, 8,
+  EGLint configAttribs[] = {EGL_RED_SIZE,  8, EGL_GREEN_SIZE, 8,
                             EGL_BLUE_SIZE, 8, EGL_NONE};
   eglChooseConfig(display, configAttribs, &config, 1, NULL);
```

2023-08-30 12:53 UTC, arduinocc04 commented
Angle을 사용하신 이유는 mac에서 EGL을 사용하기 위해서인가요?  
그렇다면 Mac인 경우와 Linux인 경우를 분리하여 Library를 붙이는 것이 나을 것 같습니다.  
Angle 설치하는 것도 귀찮고 하니까요..  

저는 Cmake의 마지막 부분을 아래와 같이 고쳐서 EGL을 붙였습니다.  
```
find_library( EGL_LIBRARY EGL "EGL 1.4 library" )
# 타겟을 링킹할 때 필요한 타겟이나 라이브러리를 지정
target_link_libraries(CH03ex
        PRIVATE
        glfw
        ${EGL_LIBRARY}
        )
```

2023-08-30 12:54 UTC, arduinocc04 commented
또한, 저는 프로젝트 이름이 glfw가 들어가도록 지어지는 것이 맞다고 생각했는데, 혹시 챕터 3과 관련하여 더 해보고 싶으신 것이 있으신건가요?

2023-08-30 13:26 UTC, howyoujini commented
> 또한, 저는 프로젝트 이름이 glfw가 들어가도록 지어지는 것이 맞다고 생각했는데, 혹시 챕터 3과 관련하여 더 해보고 싶으신 것이 있으신건가요?

저도 프로젝트 이름에 glfw 가 들어가는 것이 의도가 더 돋보이는 것 같습니다! 
이외에는 문제없어보입니다 :)

2023-08-30 13:27 UTC, howyoujini approved these changes
LGTM

2023-08-31 01:59 UTC, WongueShin commented
> Angle을 사용하신 이유는 mac에서 EGL을 사용하기 위해서인가요? 그렇다면 Mac인 경우와 Linux인 경우를 분리하여 Library를 붙이는 것이 나을 것 같습니다. Angle 설치하는 것도 귀찮고 하니까요..
> 
> 저는 Cmake의 마지막 부분을 아래와 같이 고쳐서 EGL을 붙였습니다.
> 
> ```
> find_library( EGL_LIBRARY EGL "EGL 1.4 library" )
> # 타겟을 링킹할 때 필요한 타겟이나 라이브러리를 지정
> target_link_libraries(CH03ex
>         PRIVATE
>         glfw
>         ${EGL_LIBRARY}
>         )
> ```
> 
> Cmake에서 Linux와 Apple 구분은 [이렇게](https://stackoverflow.com/a/40152725) 하면 된다고 합니다.

이 PR 의 근본적인 의도는, 크로스 플렛폼 빌드가능성을 확보하기 위함입니다!
저희 프로젝트 내부에서 관리하고 있는 의존성 관리 책임을 vcpkg 에 넘겨주기 위함인거죠.

따라서 CmakeList.txt 안에 플랫폼 분기 로직은 정말 불가피한게 아니라면 없는게 맞다고 생각합니다.

2023-08-31 02:01 UTC, WongueShin commented
> 또한, 저는 프로젝트 이름이 glfw가 들어가도록 지어지는 것이 맞다고 생각했는데, 혹시 챕터 3과 관련하여 더 해보고 싶으신 것이 있으신건가요?

두가지 이유가 있습니다.
* 크로스 플랫폼 빌드가능성에 집중한 작업 때문에, 구체적으로 어떤 패키지에 의존하는지에대한 부분에 초점울 두고있지 않습니다.
* 추후 챕터별로, 빌드가능한 예제를 만들어 올릴 예정이기 때문입니다.

2023-08-31 12:55 UTC, arduinocc04 commented
LGTM

2023-08-31 12:57 UTC, arduinocc04 approved these changes
LGTM

2023-08-31 13:05 UTC, merged