CH06 예제 코드 추가
daemyung/learn-opengl-es pull request #13
Opened 2023-09-08 12:38 UTC by WongueShin

## 🙏 Describe the pull request

index.html 에 예제 코드를 추가하고, app.ts 의 코드를 조금 수정하였습니다.

## 🖥️ System
- OS: Chrome
- GPU: WebGL2
- OpenGL: WebGL2
- EGL: WebGL2

## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [ ] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

2023-09-08 13:53 UTC, howyoujini requested changes
index.html 의 보일러플레이트를 조금 줄여볼 수 있을까요?

2023-09-08 23:24 UTC, daemyung approved these changes
LGTM

2023-09-09 15:35 UTC, WongueShin commented
> index.html 의 보일러플레이트를 조금 줄여볼 수 있을까요?

어떤 부분을 말씀하시는걸까요?

2023-09-10 08:11 UTC, ylab604 approved these changes

2023-09-12 13:24 UTC, howyoujini commented
> > index.html 의 보일러플레이트를 조금 줄여볼 수 있을까요?
> 
> 어떤 부분을 말씀하시는걸까요?

아하 제가 생각하기에는, semantic tag 가 아닌, div 로 되어있기도 하고, &nbsp 등이 쓰임으로써, 의미있는 문단을 쓰면 가독성이 좋지않을까 생각했습니다. 하지만, 이는 협업보다는 예제를 개인적으로 추가하는 것이다보니, 큰 의미가 없어보이기도 하네요! 다만, index.html 을 빌드한 브라우저를 스크린샷으로 통해 보고 싶긴합니다! 
수고하셨습니다!

2023-09-12 13:25 UTC, howyoujini approved these changes
수고하셨습니다!

2023-09-13 13:27 UTC, merged