draw regular polygon
daemyung/learn-opengl-es pull request #2
Opened 2023-07-27 12:56 UTC by arduinocc04

## 🙏 Describe the pull request

빨간색 정다각형을 화면에 그려줍니다.

## 💬 Additional context

CMake 관련 설정을 해둬서, 이 프로젝트를 복사 한다면 CMake 사용하기 편할 것 입니다.
esUtils와 다른 Include 할것들은 그냥 바깥에 뺴두는 것이 나을까요?

2023-07-27 17:22 UTC, WongueShin commented on .vscode/settings.json
> +    "cmake.sourceDirectory": "/home/arduinocc04/Documents/GitHub/learn-opengl-es"
경로가 다니엘님 로컬 환경에 기반한 절대경로로 설정되어있네요.
이부분 프로젝트 루트기반한 상대경로로 바꾸어야 할 것 같습니다.

2023-07-27 17:26 UTC, Wongyu-Shin commented on draw-regular-polygon/main.c
> +// The MIT License (MIT)
모호한 이름의 main.c 보다는 구체적인 의미를 담는게 좋아보입니다.

2023-07-27 17:32 UTC, WongueShin reviewed
코멘트 확인부탁드려요

2023-07-27 17:36 UTC, WongueShin commented on draw-regular-polygon/main.c
> +// The MIT License (MIT)
예제의 이름을 지은뒤 Exname/ex.c 이런식으로 구조를 변경하는건 어떨까요?
앞으로 추가될 많은 예제들이 프로젝트 루트에 있으면 원하는 파일을 찾기 쉽지 않을것 같습니다.

2023-07-27 17:38 UTC, Wongyu-Shin commented
@daemyung External Dir 관련해서 저희가  어떠한 컨벤션을 지켜야 할지 의견이 궁금합니다!
전 https://github.com/danginsburg/opengles3-book/  와 비교해서 특별히 다른점이 없어서 이대로 병합해도 큰 문제는 없어보여요.

2023-07-27 23:02 UTC, daemyung commented
> @daemyung External Dir 관련해서 저희가 어떠한 컨벤션을 지켜야 할지 의견이 궁금합니다! 전 https://github.com/danginsburg/opengles3-book/ 와 비교해서 특별히 다른점이 없어서 이대로 병합해도 큰 문제는 없어보여요.

외부는 외부의 컨벤션을 유지하는게 좋습니다. 혹시 pre-commit과 충돌해서 그런가요?

2023-07-28 10:51 UTC, arduinocc04 commented on draw-regular-polygon/main.c
> +// The MIT License (MIT)
아, 일단 예제 이름과 동일하게 지었습니다.

2023-07-28 12:42 UTC, WongueShin commented
> > @daemyung External Dir 관련해서 저희가 어떠한 컨벤션을 지켜야 할지 의견이 궁금합니다! 전 https://github.com/danginsburg/opengles3-book/ 와 비교해서 특별히 다른점이 없어서 이대로 병합해도 큰 문제는 없어보여요.
> 
> 외부는 외부의 컨벤션을 유지하는게 좋습니다. 혹시 pre-commit과 충돌해서 그런가요?

넵 맞습니다. 로컬에서 체크아웃해 돌리니 pre-commit 의 컨밴션과 여러부분이 충돌하네요

2023-07-28 13:00 UTC, daemyung commented
@WongueShin pre-commit 예외를 적용해도 되고 pre-commit을 적용해도 됩니다. 리뷰어 3분이서 정책을 정하세요.

2023-07-29 06:09 UTC, howyoujini reviewed
전체적으로 좋은데, 다니엘님의 어떤 OS 엔진에서 만족한 코드인지
상세한 내용이 PR 커맨트에 적혀있다면 더 리뷰하기 좋을 것 같습니다.

2023-07-29 06:15 UTC, howyoujini commented
> @WongueShin pre-commit 예외를 적용해도 되고 pre-commit을 적용해도 됩니다. 리뷰어 3분이서 정책을 정하세요.

저는 pre-commit 에 예외를 두어도 될 것 같다는 생각입니다!

2023-07-29 06:19 UTC, howyoujini requested changes
PR 을 조금 더 쪼개서 다른 사람도 예제를 올릴 수 있도록 초기세팅한 PR , 
그다음에 draw regular polygon PR 이렇게 2개로 쪼개서 올린다면 더 좋을 것 같네요!

2023-07-29 06:31 UTC, WongueShin commented
> > @WongueShin pre-commit 예외를 적용해도 되고 pre-commit을 적용해도 됩니다. 리뷰어 3분이서 정책을 정하세요.
> 
> 저는 pre-commit 에 예외를 두어도 될 것 같다는 생각입니다!

좋습니다 저도 동감해요.

2023-07-29 06:43 UTC, arduinocc04 commented
> PR 을 조금 더 쪼개서 다른 사람도 예제를 올릴 수 있도록 초기세팅한 PR , 
> 
> 그다음에 draw regular polygon PR 이렇게 2개로 쪼개서 올린다면 더 좋을 것 같네요!

esUtils, egl같은 외부 라이브러리를 밖으로 빼시기를 원하시는건가요?

지금은 제 프로젝트에 외부 라이브러리를 다 넣어둬서 쪼개기 쉽지 않을 것 같습니다.

2023-07-29 06:47 UTC, WongueShin commented
> > PR 을 조금 더 쪼개서 다른 사람도 예제를 올릴 수 있도록 초기세팅한 PR ,
> > 그다음에 draw regular polygon PR 이렇게 2개로 쪼개서 올린다면 더 좋을 것 같네요!
> 
> esUtils, egl같은 외부 라이브러리를 밖으로 빼시기를 원하시는건가요?
> 
> 지금은 제 프로젝트에 외부 라이브러리를 다 넣어둬서 쪼개기 쉽지 않을 것 같습니다.

지금 올리신 PR 작업분의 내용을 정리해보면
1. 현 저장소에 OpenGl 개발 환경을 설정.
2. 교재의 Hello triangle 예제를 추가한다.
3. 다니엘님이 작성하신 다각형 예제를 추가한다.

총 3개의 작업으로 정리할 수 있는데, 작업단위로 PR 을 구분하자는 말씀이신것 같습니다.
1. OpenGL 개발환경 설정
2. 예제 추가. 
이정도로 구분하면 깔끔할 것 같네요!

@howyoujini  제가 의도를 잘 이해한게 맞을까요?

2023-07-29 06:55 UTC, arduinocc04 commented
> 전체적으로 좋은데, 다니엘님의 어떤 OS 엔진에서 만족한 코드인지
> 
> 상세한 내용이 PR 커맨트에 적혀있다면 더 리뷰하기 좋을 것 같습니다.

관련 템플릿을 만들어두는 것이 좋을 것 같습니다

2023-07-29 06:56 UTC, howyoujini commented
> > 전체적으로 좋은데, 다니엘님의 어떤 OS 엔진에서 만족한 코드인지
> > 상세한 내용이 PR 커맨트에 적혀있다면 더 리뷰하기 좋을 것 같습니다.
> 
> 관련 템플릿을 만들어두는 것이 좋을 것 같습니다. 일단 수정해두긴 했어요.

네 ! 확인했습니다. 좋습니다!

2023-07-29 06:58 UTC, howyoujini commented
> 관련 템플릿을 만들어두는 것이 좋을 것 같습니다.
> 일단 수정해두긴 했어요.

2023-07-29 06:58 UTC, arduinocc04 commented
일단 다들 esUtils 라이브러리를 사용하실 계획이신가요?

2023-07-29 06:59 UTC, howyoujini commented
> > > PR 을 조금 더 쪼개서 다른 사람도 예제를 올릴 수 있도록 초기세팅한 PR ,
> > > 그다음에 draw regular polygon PR 이렇게 2개로 쪼개서 올린다면 더 좋을 것 같네요!
> > 
> > 
> > esUtils, egl같은 외부 라이브러리를 밖으로 빼시기를 원하시는건가요?
> > 지금은 제 프로젝트에 외부 라이브러리를 다 넣어둬서 쪼개기 쉽지 않을 것 같습니다.
> 
> 지금 올리신 PR 작업분의 내용을 정리해보면
> 
> 1. 현 저장소에 OpenGl 개발 환경을 설정.
> 2. 교재의 Hello triangle 예제를 추가한다.
> 3. 다니엘님이 작성하신 다각형 예제를 추가한다.
> 
> 총 3개의 작업으로 정리할 수 있는데, 작업단위로 PR 을 구분하자는 말씀이신것 같습니다.
> 
> 1. OpenGL 개발환경 설정
> 2. 예제 추가.
>    이정도로 구분하면 깔끔할 것 같네요!
> 
> @howyoujini 제가 의도를 잘 이해한게 맞을까요?

네 정확히 맞습니다~!

2023-07-29 07:00 UTC, howyoujini commented
> esUtils

네.. 우선 저는 활용해보려고 합니다. 사실 뭐가 뭔지 잘 몰라서 이것저것 활용해보려구요!

2023-07-29 07:03 UTC, arduinocc04 commented
그럼 그냥 esUtils랑 다른 include 할것들 밖으로 빼서 새로 pull request 올리겠습니다.

지금 구조가 제 프로젝트 폴더 안에 저런 include 할것들을 다 넣어놔서, Cmake 설정도 그렇게 맞춰져있어서 중간에 나누기가 애매합니다.

저런 include 할것들을 밖으로 빼면 훨씬 깔끔하고, 다른 분들도 사용하기 편할거예요.

2023-07-29 07:27 UTC, howyoujini commented
별 문제 없다면 이대로 merge 해도 될 것 같아요.

> 

네 좋아요. 다니엘님 감사합니다!

2023-07-29 07:28 UTC, howyoujini commented
> 그럼 그냥 esUtils랑 다른 include 할것들 밖으로 빼서 새로 pull request 올리겠습니다.
> 
> 지금 구조가 제 프로젝트 폴더 안에 저런 include 할것들을 다 넣어놔서, Cmake 설정도 그렇게 맞춰져있어서 중간에 나누기가 애매합니다.
> 
> 저런 include 할것들을 밖으로 빼면 훨씬 깔끔하고, 다른 분들도 사용하기 편할거예요.

네 좋아요. 다니엘님 감사합니다!

2023-07-30 07:50 UTC, closed without merging